//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UILabel;

@interface _ASPurchasedCellContentView : UIView
{
    UILabel *_subtitleLabel;
    UILabel *_subtitle2Label;
    UILabel *_restrictionsLabel;
    UILabel *_titleLabel;
    NSString *_text;
}

@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *restrictionsLabel; // @synthesize restrictionsLabel=_restrictionsLabel;
@property(retain, nonatomic) UILabel *subtitle2Label; // @synthesize subtitle2Label=_subtitle2Label;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
- (void).cxx_destruct;
- (void)setBackgroundColor:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly, nonatomic) NSString *subtitle2;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) NSString *restrictionsText;
@property(readonly, nonatomic) NSString *subtitle;
- (id)initWithFrame:(struct CGRect)arg1;

@end

