//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol ASAdFrequencyCapping;

@interface ASAdFrequencyCapper : NSObject
{
    _Bool _frequencyCappingEnabled;
    id <ASAdFrequencyCapping> _frequencyCappingObject;
    NSMutableSet *_impressedImpressionIdentifiers;
}

@property(readonly, nonatomic) NSMutableSet *impressedImpressionIdentifiers; // @synthesize impressedImpressionIdentifiers=_impressedImpressionIdentifiers;
@property(nonatomic, getter=isFrequencyCappingEnabled) _Bool frequencyCappingEnabled; // @synthesize frequencyCappingEnabled=_frequencyCappingEnabled;
@property(retain, nonatomic) id <ASAdFrequencyCapping> frequencyCappingObject; // @synthesize frequencyCappingObject=_frequencyCappingObject;
- (void).cxx_destruct;
- (void)_updateSearchCapping:(id)arg1;
- (void)dealloc;
- (id)init;

@end

