//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASAdTargetingHeaderStore-Protocol.h"

@class NSString;
@protocol ASAdTargetingHeaderStore;

@interface ASAdHeaderInjector : NSObject <ASAdTargetingHeaderStore>
{
    id <ASAdTargetingHeaderStore> _headerStore;
}

@property(retain, nonatomic) id <ASAdTargetingHeaderStore> headerStore; // @synthesize headerStore=_headerStore;
- (void).cxx_destruct;
- (void)fetchIAdIDWithCompletion:(CDUnknownBlockType)arg1;
- (void)setValue:(id)arg1 forHTTPHeaderField:(id)arg2;
- (void)stopConfiguringToroHeaders;
- (void)startConfiguringToroHeaders;
- (void)_changeToroHeaders;
- (void)dealloc;
- (id)initWithHeaderStore:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

