//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASADTargetingTimerProxyFireable-Protocol.h"

@class NSString;
@protocol ASADTargetingTimerProxyFireable;

@interface ASADTargetingTimerProxy : NSObject <ASADTargetingTimerProxyFireable>
{
    id <ASADTargetingTimerProxyFireable> _timerTarget;
}

@property(nonatomic) __weak id <ASADTargetingTimerProxyFireable> timerTarget; // @synthesize timerTarget=_timerTarget;
- (void).cxx_destruct;
- (void)as_ADTargetingTimerProxyTimerFired:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

