//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ADAdEnablingTester-Protocol.h"

@class NSLock, NSString, SKUIConfigurationPreloader, SSAccountStore;
@protocol OS_dispatch_group;

@interface ASAdEnablingSpeedTester : NSObject <ADAdEnablingTester>
{
    _Bool _inProcessAdsEnabledValue;
    _Bool _shouldGiveInProcessAnswer;
    SSAccountStore *_accountStore;
    NSLock *_inProcessAnswerLock;
    NSObject<OS_dispatch_group> *_dispatchGroup;
    SKUIConfigurationPreloader *_preloader;
}

@property(retain, nonatomic) SKUIConfigurationPreloader *preloader; // @synthesize preloader=_preloader;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *dispatchGroup; // @synthesize dispatchGroup=_dispatchGroup;
@property(retain, nonatomic) NSLock *inProcessAnswerLock; // @synthesize inProcessAnswerLock=_inProcessAnswerLock;
@property(nonatomic) _Bool shouldGiveInProcessAnswer; // @synthesize shouldGiveInProcessAnswer=_shouldGiveInProcessAnswer;
@property(nonatomic) _Bool inProcessAdsEnabledValue; // @synthesize inProcessAdsEnabledValue=_inProcessAdsEnabledValue;
@property(retain, nonatomic) SSAccountStore *accountStore; // @synthesize accountStore=_accountStore;
- (void).cxx_destruct;
- (_Bool)_outOfProcessIsAdsEnabledForStorefront;
- (_Bool)_inProcessIsAdsEnabledForStorefront;
- (_Bool)isAdsEnabledForStorefront;
- (_Bool)isManagedAppleID;
- (id)initWithConfigurationPreloader:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

