//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "CLLocationManagerDelegate-Protocol.h"
#import "SKUIAdvertisingSelectionTargetAction-Protocol.h"
#import "SKUIApplicationDelegate-Protocol.h"
#import "SKUIMetricsApplicationDelegate-Protocol.h"
#import "UIApplicationTestingDelegate-Protocol.h"

@class ASApplicationController, ASLaunchNotificationsController, NSMutableArray, NSString, SKUIURL, UIWindow;

@interface ASAppDelegate : UIResponder <SKUIAdvertisingSelectionTargetAction, CLLocationManagerDelegate, SKUIApplicationDelegate, UIApplicationTestingDelegate, SKUIMetricsApplicationDelegate>
{
    ASApplicationController *_applicationController;
    _Bool _didDisplayFirstPage;
    ASLaunchNotificationsController *_launchNotificationsController;
    SKUIURL *_launchURL;
    long long _networkStartCount;
    _Bool _onActiveShouldResumeApplication;
    NSMutableArray *_presentationQueue;
    CDUnknownBlockType _quickActionBlock;
    UIWindow *_window;
}

- (void).cxx_destruct;
- (void)_showTransientViewController:(id)arg1;
- (void)_showExternalURL:(id)arg1;
- (void)_showEULAViewControllerWithURL:(id)arg1;
- (void)_showBlankPlaceholderViewController;
- (void)_selectUpdatesTab;
- (_Bool)_runTestWithName:(id)arg1 options:(id)arg2 tabBarIndex:(long long)arg3;
- (_Bool)_runLaunchTestWithName:(id)arg1 options:(id)arg2;
- (void)_openURL:(id)arg1 sourceApplication:(id)arg2 annotation:(id)arg3;
- (id)_newDefaultTabBarItemsWithClientContext:(id)arg1 style:(long long)arg2;
- (void)_lookupProductURLForBundleIdentifier:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)_handleNonHostProductURL:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)_loadApplicationWithLaunchOptions:(id)arg1;
- (void)_networkingStopNotification:(id)arg1;
- (void)_networkingStartNotification:(id)arg1;
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)applicationDidBecomeActive:(id)arg1;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)application:(id)arg1 didReselectTabBarItem:(id)arg2;
- (id)application:(id)arg1 navigationControllerWithTabBarItem:(id)arg2;
- (void)application:(id)arg1 willTransitionToSize:(struct CGSize)arg2 withTransitionCoordinator:(id)arg3;
- (void)application:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)applicationDidDisplayFirstPage:(id)arg1;
- (void)applicationDidChangeClientContext:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)skuiadvertising_advertWasSelected:(id)arg1;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)_askForLocationPermission;
- (void)askForLocationPermissionIfNeeded;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

