//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIViewController.h>

#import "ASChildPurchasedViewController-Protocol.h"
#import "SKUIItemListTableDelegate-Protocol.h"
#import "SKUIViewControllerTesting-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"

@class ASPurchasedPage, NSString, SKUIItemListTableViewController, SKUISegmentedTableHeaderView, UISearchBar, UISegmentedControl, _UIContentUnavailableView;
@protocol ASChildPurchasedViewControllerDelegate;

@interface ASBaseIPhonePurchasedViewController : SKUIViewController <SKUIItemListTableDelegate, SKUIViewControllerTesting, UISearchBarDelegate, ASChildPurchasedViewController>
{
    id <ASChildPurchasedViewControllerDelegate> _delegate;
    NSString *_familyMemberNoiTunesAccountActionURL;
    _UIContentUnavailableView *_familyMemberNoiTunesAccountView;
    SKUISegmentedTableHeaderView *_headerView;
    _UIContentUnavailableView *_noPurchasedPageView;
    ASPurchasedPage *_page;
    UISearchBar *_searchBar;
    UISegmentedControl *_segmentedControl;
    SKUIItemListTableViewController *_tableViewController;
    _Bool _shouldShowFilterHeader;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
@property(nonatomic) _Bool shouldShowFilterHeader; // @synthesize shouldShowFilterHeader=_shouldShowFilterHeader;
@property(retain, nonatomic) ASPurchasedPage *page; // @synthesize page=_page;
@property(nonatomic) __weak id <ASChildPurchasedViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_messagesImageConsumer;
- (id)_imageConsumer;
- (id)_tableViewController;
- (id)_noPurchasedPageView;
- (id)_familyMemberNoiTunesAccountView;
- (id)_headerView;
- (Class)_cellClass;
- (void)_segmentedControlAction:(id)arg1;
- (void)_signInAction;
- (void)_familyMemberNoiTunesAccountAction;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (_Bool)performTestWithName:(id)arg1 options:(id)arg2;
- (void)itemListWillBeginDragging:(id)arg1;
- (id)itemList:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)itemList:(id)arg1 didSelectItem:(id)arg2 atIndexPath:(id)arg3;
- (void)itemList:(id)arg1 didRemoveItemAtIndexPath:(id)arg2;
- (_Bool)itemList:(id)arg1 canRemoveItemAtIndexPath:(id)arg2;
- (void)reloadData;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

