//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIViewController.h>

#import "ASChildPurchasedViewController-Protocol.h"
#import "SKUIItemGridDelegate-Protocol.h"
#import "SKUIMenuViewControllerDelegate-Protocol.h"
#import "SKUIMessageBannerDelegate-Protocol.h"
#import "SKUIProductPageOverlayDelegate-Protocol.h"
#import "SKUIViewControllerTesting-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"

@class ASPurchasedHeaderView, ASPurchasedPage, NSArray, NSString, SKUIItemGridViewController, SKUIMessageBanner, SKUIProductPageOverlayController, SSFamilyMember, UIPopoverController, _UIContentUnavailableView;
@protocol ASChildPurchasedViewControllerDelegate;

@interface ASBaseIPadPurchasedViewController : SKUIViewController <SKUIItemGridDelegate, SKUIMenuViewControllerDelegate, SKUIProductPageOverlayDelegate, SKUIViewControllerTesting, UIPopoverControllerDelegate, UISearchBarDelegate, SKUIMessageBannerDelegate, ASChildPurchasedViewController>
{
    id <ASChildPurchasedViewControllerDelegate> _delegate;
    ASPurchasedPage *_page;
    UIPopoverController *_deviceTypeMenuPopover;
    UIPopoverController *_familyMemberMenuPopover;
    NSString *_familyMemberNoiTunesAccountActionURL;
    long long _familyAlertReason;
    _UIContentUnavailableView *_familyMemberNoiTunesAccountView;
    ASPurchasedHeaderView *_headerView;
    SKUIItemGridViewController *_itemGridViewController;
    _UIContentUnavailableView *_noPurchasedPageView;
    SKUIProductPageOverlayController *_overlayController;
    long long _overlaySourceItemIndex;
    SKUIMessageBanner *_banner;
    NSArray *_sortedFamilyMembers;
    SSFamilyMember *_activeFamilyMember;
    _Bool _shouldShowFilterHeader;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
@property(nonatomic) _Bool shouldShowFilterHeader; // @synthesize shouldShowFilterHeader=_shouldShowFilterHeader;
@property(nonatomic) __weak id <ASChildPurchasedViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ASPurchasedPage *page; // @synthesize page=_page;
- (void).cxx_destruct;
- (void)_setFamilyBarButtonItem;
- (Class)_cellClass;
- (id)_imageConsumer;
- (id)_itemGridViewController;
- (id)_popSourceViewForOverlayController:(id)arg1;
- (id)_noPurchasedPageView;
- (id)_newMenuPopoverWithTitles:(id)arg1 images:(id)arg2 title:(id)arg3 checkedIndex:(long long)arg4;
- (id)_familyMemberNoiTunesAccountView;
- (id)_headerView;
- (void)_filterLocalAppsAction:(id)arg1;
- (void)_familyButtonAction:(id)arg1;
- (void)_deviceTypeButtonAction:(id)arg1;
- (void)_signInAction;
- (void)_familyMemberNoiTunesAccountAction;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)askPermissionBannerDidClear:(id)arg1;
- (void)askPermissionBannerDidSelect:(id)arg1;
- (void)productPageOverlayDidDismiss:(id)arg1;
- (id)productPageOverlay:(id)arg1 flipSourceViewToPresentItem:(id)arg2;
- (id)productPageOverlay:(id)arg1 flipSourceViewToDismissItem:(id)arg2;
- (void)menuViewController:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)itemGridWillBeginDragging:(id)arg1;
- (void)itemGrid:(id)arg1 didSelectItem:(id)arg2 atIndex:(long long)arg3;
- (void)itemGrid:(id)arg1 didPerformEditActionForItem:(id)arg2 atIndex:(long long)arg3;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)reloadData;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

