//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SKUIClientContext;

@interface ASBaseTabBarBuilder : NSObject
{
    SKUIClientContext *_clientContext;
    long long _style;
}

@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
- (void).cxx_destruct;
- (_Bool)configureTabBarItem:(id)arg1 withLocalizationProvider:(CDUnknownBlockType)arg2;
- (id)buildWithDefaultItems:(id)arg1 shouldLoadItemsFromStore:(_Bool)arg2;
- (id)initWithContext:(id)arg1 style:(long long)arg2;

@end

