//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIViewController.h>

#import "ASChildPurchasedViewControllerDelegate-Protocol.h"
#import "SKUIViewControllerTesting-Protocol.h"
#import "UIViewControllerRestoration-Protocol.h"

@class ASBaseIPadPurchasedViewController, ASBaseIPhonePurchasedViewController, ASPurchasedPage, NSString, SSFamilyMember, UIImageView;

@interface ASBasePurchasedViewController : SKUIViewController <ASChildPurchasedViewControllerDelegate, SKUIViewControllerTesting, UIViewControllerRestoration>
{
    UIImageView *_animationImageView;
    long long _deviceType;
    SSFamilyMember *_familyMember;
    _Bool _hidesInstalledApps;
    ASBaseIPadPurchasedViewController *_iPadViewController;
    ASBaseIPhonePurchasedViewController *_iPhoneViewController;
    ASPurchasedPage *_page;
    NSString *_searchTerm;
}

+ (long long)_sizeClassForSize:(struct CGSize)arg1;
+ (id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2;
+ (_Bool)_shouldForwardViewWillTransitionToSize;
@property(retain, nonatomic) SSFamilyMember *familyMember; // @synthesize familyMember=_familyMember;
- (void).cxx_destruct;
- (void)_reloadView;
- (void)_reloadViewControllerWithSize:(struct CGSize)arg1;
- (void)_reloadData;
- (void)_reloadDataAndCheckForUpdates;
- (id)_newIPadViewController;
- (id)_newIPhoneViewController;
- (_Bool)_isSignInRequired;
- (id)_createPurchasedPage;
- (id)_additionalPredicatesForPurchaseDB;
- (void)_familyCircleDidChange:(id)arg1;
- (void)_accountStoreDidChange:(id)arg1;
- (void)_databaseStateChangedNotification:(id)arg1;
- (void)childPurchasedViewControllerWantsAuthenticate:(id)arg1;
- (void)childPurchasedViewController:(id)arg1 didChangeHidesInstalledApps:(_Bool)arg2;
- (void)childPurchasedViewController:(id)arg1 didChangeDeviceType:(long long)arg2;
- (void)childPurchasedViewController:(id)arg1 didChangeFamilyMember:(id)arg2;
- (void)childPurchasedViewController:(id)arg1 didChangeSearchTerm:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

