//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"

@class NSIndexPath, NSString, SKUIClientContext, UIImage;
@protocol ASCategoriesDatasourceDelegate, ASCategoryProtocol;

@protocol ASCategoriesDatasourceProtocol <NSObject, UICollectionViewDataSource>
@property(nonatomic) _Bool excludesNearby;
@property(nonatomic) _Bool showIcons;
@property(retain, nonatomic) Class artworkLoaderClass;
@property(retain, nonatomic) UIImage *fallbackImage;
@property(nonatomic) _Bool showDisclosureByDefault;
@property(copy, nonatomic) NSString *title;
@property(retain, nonatomic) SKUIClientContext *clientContext;
@property(nonatomic) __weak id <ASCategoriesDatasourceDelegate> delegate;
- (NSIndexPath *)indexPathForCategory:(id <ASCategoryProtocol>)arg1;
- (NSString *)titleForSection:(unsigned long long)arg1;
- (unsigned long long)headerTypeForSection:(unsigned long long)arg1;
- (void)fetchCategories;
- (NSString *)categoryTitleAtIndexPath:(NSIndexPath *)arg1;
- (id <ASCategoryProtocol>)categoryAtIndexPath:(NSIndexPath *)arg1;
- (_Bool)canDisplayDrillInForCategoryAtIndexPath:(NSIndexPath *)arg1;
@end

