//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol ASCategoriesControllerProtocol, ASCategoryProtocol;

@protocol ASCategoriesControllerDelegate <NSObject>
- (void)categoriesController:(id <ASCategoriesControllerProtocol>)arg1 selectedCategoryForSubmenu:(id <ASCategoryProtocol>)arg2;
- (void)categoriesController:(id <ASCategoriesControllerProtocol>)arg1 selectedCategoryForDisplay:(id <ASCategoryProtocol>)arg2;

@optional
- (void)categoriesControllerEndedLoading:(id <ASCategoriesControllerProtocol>)arg1;
- (void)categoriesControllerBeganLoading:(id <ASCategoriesControllerProtocol>)arg1;
@end

