//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@interface ASCategoriesLeftNavigationController : UINavigationController
{
    unsigned long long _pushCount;
}

@property(nonatomic) unsigned long long pushCount; // @synthesize pushCount=_pushCount;
- (void)_resetPushCount;
- (void)_incrementPushCount;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (id)init;

@end

