//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSString, UICollectionView;
@protocol ASCategoriesControllerDelegate, ASCategoriesDatasourceProtocol, ASCategoryProtocol;

@protocol ASCategoriesControllerProtocol <NSObject, UICollectionViewDelegate>
@property(retain, nonatomic) id <ASCategoryProtocol> selectedCategory;
@property(nonatomic) struct CGSize viewSize;
@property(readonly, copy, nonatomic) NSString *title;
@property(retain, nonatomic) UICollectionView *collectionView;
@property(readonly, nonatomic) id <ASCategoriesDatasourceProtocol> categoriesDatasource;
@property(nonatomic) __weak id <ASCategoriesControllerDelegate> delegate;
- (void)toggleSelectionHighlight:(_Bool)arg1;
- (void)fetchDatasourceIgnoringCache:(_Bool)arg1;
- (id)initWithDatasource:(id <ASCategoriesDatasourceProtocol>)arg1;
@end

