//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ASCategoriesBaseDatasource.h"

#import "ISOperationDelegate-Protocol.h"

@class NSArray, NSOperationQueue, NSString;
@protocol ASCategoriesDatasourceDelegate;

@interface ASCategoriesDatasource : ASCategoriesBaseDatasource <ISOperationDelegate>
{
    NSOperationQueue *_operationQueue;
    Class _networkingClass;
    id <ASCategoriesDatasourceDelegate> _delegate;
    NSArray *_promotedCategories;
    NSArray *_categories;
}

@property(readonly, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(readonly, copy, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property(readonly, copy, nonatomic) NSArray *promotedCategories; // @synthesize promotedCategories=_promotedCategories;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void).cxx_destruct;
- (void)_primeIconImages;
- (unsigned long long)numberOfItemsInSection:(unsigned long long)arg1;
- (unsigned long long)numberOfSections;
- (void)updateDataSourceForLocationStatuschange:(_Bool)arg1;
- (void)operation:(id)arg1 failedWithError:(id)arg2;
- (void)operationFinished:(id)arg1;
- (void)operationWillStart:(id)arg1;
- (void)fetchCategories;
- (id)titleForSection:(unsigned long long)arg1;
- (unsigned long long)headerTypeForSection:(unsigned long long)arg1;
- (id)categoryTitleAtIndexPath:(id)arg1;
- (id)categoryAtIndexPath:(id)arg1;
- (_Bool)canDisplayDrillInForCategoryAtIndexPath:(id)arg1;
- (id)initWithNetworkingClass:(Class)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

