//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIViewController.h>

#import "ASCategoriesControllerDelegate-Protocol.h"

@class IKJSNavigationDocument, JSManagedValue, NSObject, NSString, SKUILoadingView, UICollectionView;
@protocol ASCategoriesControllerProtocol, ASCategoriesSelectionViewControllerDelegate, OS_dispatch_source;

@interface ASCategoriesSelectionViewController : SKUIViewController <ASCategoriesControllerDelegate>
{
    JSManagedValue *_managedNavigationDocument;
    IKJSNavigationDocument *_navigationDocument;
    SKUILoadingView *_loadingView;
    NSObject<OS_dispatch_source> *_loadingTimeoutTimer;
    _Bool _highlightsSelection;
    UICollectionView *_collectionView;
    id <ASCategoriesControllerProtocol> _categoriesController;
    id <ASCategoriesSelectionViewControllerDelegate> _delegate;
}

+ (Class)categoryCellClass;
+ (id)categoriesDataSourceProtocolOverride;
@property(nonatomic) _Bool highlightsSelection; // @synthesize highlightsSelection=_highlightsSelection;
@property(nonatomic) __weak id <ASCategoriesSelectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id <ASCategoriesControllerProtocol> categoriesController; // @synthesize categoriesController=_categoriesController;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)_clearCollectionViewSelections;
- (void)_hideLoadingView;
- (void)_showLoadingView;
- (void)_startLoadingTimer;
- (void)categoriesControllerEndedLoading:(id)arg1;
- (void)categoriesControllerBeganLoading:(id)arg1;
- (void)categoriesController:(id)arg1 selectedCategoryForSubmenu:(id)arg2;
- (void)categoriesController:(id)arg1 selectedCategoryForDisplay:(id)arg2;
- (void)setClientContext:(id)arg1;
- (void)refetchIgnoringCache:(_Bool)arg1;
- (void)handleNearMeLocationStatusChange:(_Bool)arg1;
- (void)selectedCategory:(id)arg1;
- (void)dealloc;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (id)initWithController:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

