//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, UIView;

@interface ASCategoryCollectionViewCell : UICollectionViewCell
{
    _Bool _showChevron;
    _Bool _showIcon;
    UILabel *_titleLabel;
    UIImageView *_imageView;
    UIView *_bottomBorder;
    UIImageView *_chevronImageView;
}

+ (struct CGSize)_iconSize;
@property(readonly, nonatomic) UIImageView *chevronImageView; // @synthesize chevronImageView=_chevronImageView;
@property(readonly, nonatomic) UIView *bottomBorder; // @synthesize bottomBorder=_bottomBorder;
@property(nonatomic) _Bool showIcon; // @synthesize showIcon=_showIcon;
@property(nonatomic) _Bool showChevron; // @synthesize showChevron=_showChevron;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)_configureSubviews;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

