//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSError;
@protocol ASCategoriesDatasourceProtocol;

@protocol ASCategoriesDatasourceDelegate <NSObject>
- (void)categoriesDatasource:(id <ASCategoriesDatasourceProtocol>)arg1 dataChangedAt:(NSArray *)arg2;
- (void)categoriesDatasource:(id <ASCategoriesDatasourceProtocol>)arg1 failedToLoad:(NSError *)arg2;
- (void)categoriesDatasourceEndedLoading:(id <ASCategoriesDatasourceProtocol>)arg1;
- (void)categoriesDatasourceBeganLoading:(id <ASCategoriesDatasourceProtocol>)arg1;
@end

