//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASCategoriesControllerProtocol-Protocol.h"
#import "ASCategoriesDatasourceDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSString, UICollectionView;
@protocol ASCategoriesControllerDelegate, ASCategoriesDatasourceProtocol, ASCategoryProtocol;

@interface ASCategoriesController : NSObject <ASCategoriesDatasourceDelegate, UICollectionViewDelegateFlowLayout, ASCategoriesControllerProtocol>
{
    NSString *_title;
    _Bool _loadingData;
    _Bool _hasCachedData;
    id <ASCategoriesDatasourceProtocol> _categoriesDatasource;
    UICollectionView *_collectionView;
    id <ASCategoriesControllerDelegate> _delegate;
    id <ASCategoryProtocol> _selectedCategory;
    struct CGSize _viewSize;
}

@property(retain, nonatomic) id <ASCategoryProtocol> selectedCategory; // @synthesize selectedCategory=_selectedCategory;
@property(nonatomic) struct CGSize viewSize; // @synthesize viewSize=_viewSize;
@property(nonatomic) __weak id <ASCategoriesControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(readonly, nonatomic) id <ASCategoriesDatasourceProtocol> categoriesDatasource; // @synthesize categoriesDatasource=_categoriesDatasource;
- (void).cxx_destruct;
- (void)_refetchData;
- (void)_storefrontDidChangeNotification:(id)arg1;
- (_Bool)_collectionViewHasCells;
- (void)categoriesDatasource:(id)arg1 dataChangedAt:(id)arg2;
- (void)categoriesDatasource:(id)arg1 failedToLoad:(id)arg2;
- (void)categoriesDatasourceEndedLoading:(id)arg1;
- (void)categoriesDatasourceBeganLoading:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)toggleSelectionHighlight:(_Bool)arg1;
- (void)fetchDatasourceIgnoringCache:(_Bool)arg1;
@property(readonly, copy, nonatomic) NSString *title;
- (void)dealloc;
- (id)initWithDatasource:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

