//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SSFamilyMember;
@protocol ASChildPurchasedViewController;

@protocol ASChildPurchasedViewControllerDelegate <NSObject>
- (void)childPurchasedViewControllerWantsAuthenticate:(id <ASChildPurchasedViewController>)arg1;
- (void)childPurchasedViewController:(id <ASChildPurchasedViewController>)arg1 didChangeHidesInstalledApps:(_Bool)arg2;
- (void)childPurchasedViewController:(id <ASChildPurchasedViewController>)arg1 didChangeDeviceType:(long long)arg2;
- (void)childPurchasedViewController:(id <ASChildPurchasedViewController>)arg1 didChangeFamilyMember:(SSFamilyMember *)arg2;
- (void)childPurchasedViewController:(id <ASChildPurchasedViewController>)arg1 didChangeSearchTerm:(NSString *)arg2;
@end

