//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUITableViewCell.h>

@class NSString, UIImage, UIImageView;

@interface ASFamilyMemberTableViewCell : SKUITableViewCell
{
    UIImage *_arrowImage;
    UIImage *_highlightedArrowImage;
    UIImageView *_arrowImageView;
}

- (void).cxx_destruct;
- (void)_reloadHighlightState;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
@property(retain, nonatomic) UIImage *image;
@property(copy, nonatomic) NSString *title;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

