//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSError;

@protocol ASFetchCategoriesOperationProtocol <NSObject>
@property(readonly, nonatomic) _Bool excludesArtwork;
@property(readonly, nonatomic) _Bool excludesNearby;
@property(readonly, nonatomic) NSError *error;
@property(readonly, copy, nonatomic) NSArray *categories;
@property(readonly, copy, nonatomic) NSArray *promotedCategories;
@end

