//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIImage;
@protocol ASItemArtworkLoaderProtocolDelegate, SKUIArtworkProviding;

@protocol ASItemArtworkLoaderProtocol <NSObject>
@property(nonatomic) __weak id <ASItemArtworkLoaderProtocolDelegate> delegate;
@property(readonly, nonatomic) UIImage *placeholderImage;
- (UIImage *)styledImageForImage:(UIImage *)arg1;
- (UIImage *)imageForArtworkProvider:(id <SKUIArtworkProviding>)arg1 reason:(long long)arg2;
- (UIImage *)imageForArtworkProvider:(id <SKUIArtworkProviding>)arg1;
@end

