//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AAUIFamilySetupPrompter, NSOperationQueue, SKUIClientContext, UIViewController;

@interface ASLaunchNotificationsController : NSObject
{
    SKUIClientContext *_clientContext;
    AAUIFamilySetupPrompter *_familySetupPrompter;
    NSOperationQueue *_operationQueue;
    UIViewController *_parentViewController;
}

@property(retain, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
- (void).cxx_destruct;
- (void)_showFamilySetupPrompt;
- (_Bool)_hasDisplayedFamilySetup;
- (void)checkForNotifications;
- (id)initWithParentViewController:(id)arg1;

@end

