//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SKUIClientContext, SKUILoadingView;

@interface ASLoadingViewController : UIViewController
{
    SKUIClientContext *_clientContext;
    SKUILoadingView *_loadingView;
}

@property(retain, nonatomic) SKUILoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(readonly, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithClientContext:(id)arg1;

@end

