//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIViewController.h>

#import "CLLocationManagerDelegate-Protocol.h"
#import "SKUIItemListTableDelegate-Protocol.h"
#import "SKUIItemStateCenterObserver-Protocol.h"
#import "SKUIMetricsViewController-Protocol.h"
#import "SKUIViewControllerTesting-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class ASNearMeOptInView, CLLocationManager, NSArray, NSObject, NSString, SKUIItemList, SKUIItemListTableViewController, SKUILoadingView, SKUIMetricsController, SKUIStorePageViewController, SSLookupRequest, SSMetricsConfiguration, SSMetricsPageEvent, UIRefreshControl, _UIContentUnavailableView;
@protocol OS_dispatch_source;

@interface ASNearMeViewController : SKUIViewController <CLLocationManagerDelegate, SKUIItemListTableDelegate, SKUIItemStateCenterObserver, SKUIMetricsViewController, SKUIViewControllerTesting, UIAlertViewDelegate>
{
    NSArray *_allItems;
    _Bool _isMonitoring;
    SKUIStorePageViewController *_ipadViewController;
    SKUIItemListTableViewController *_iphoneViewController;
    SKUIItemList *_itemList;
    SSMetricsPageEvent *_lastPageEvent;
    SKUILoadingView *_loadingView;
    NSObject<OS_dispatch_source> *_loadingTimeoutTimer;
    CLLocationManager *_locationManager;
    long long _locationTimeoutCount;
    NSObject<OS_dispatch_source> *_locationTimeoutTimer;
    SSLookupRequest *_lookupRequest;
    SKUIMetricsController *_metricsController;
    _UIContentUnavailableView *_noResultsView;
    ASNearMeOptInView *_optInView;
    SSMetricsConfiguration *_pageMetricsConfiguration;
    NSString *_performanceTestName;
    UIRefreshControl *_refreshControl;
    NSObject<OS_dispatch_source> *_refreshTimer;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
- (void).cxx_destruct;
- (void)_turnOffGenius;
- (void)_timeoutLocation;
- (void)_startTimeoutTimer;
- (void)_startRefreshTimer;
- (void)_startLoadingTimer;
- (void)_showPlatformViewController;
- (void)_showLoadingView;
- (void)_setMetricsController:(id)arg1;
- (void)_setChildView:(id)arg1;
- (void)_removePlaceholderViews;
- (void)_reloadWithItems:(id)arg1 reason:(long long)arg2;
- (void)_reloadTabBarItemsForAlert:(_Bool)arg1;
- (void)_refreshResults;
- (id)_refreshControl;
- (id)_platformViewController;
- (id)_optInView;
- (id)_noResultsViewWithReason:(long long)arg1;
- (_Bool)_isQualityLocation:(id)arg1;
- (id)_iphoneViewController;
- (id)_ipadViewController;
- (void)_hideLoadingView;
- (void)_finishLookupForLocation:(id)arg1 withItems:(id)arg2 response:(id)arg3 error:(id)arg4;
- (id)_filteredItemsWithItems:(id)arg1;
- (void)_fetchItemsForLocation:(id)arg1;
- (void)_metricsEnterEventNotification:(id)arg1;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)_turnOnGenius:(id)arg1;
- (void)_pullToRefreshAction:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)alertViewCancel:(id)arg1;
- (_Bool)performTestWithName:(id)arg1 options:(id)arg2;
- (id)activeMetricsController;
- (void)itemStateCenterRestrictionsChanged:(id)arg1;
- (void)itemList:(id)arg1 willDisplayCellForItem:(id)arg2 atIndexPath:(id)arg3;
- (void)itemList:(id)arg1 didSelectItem:(id)arg2 atIndexPath:(id)arg3;
- (id)itemList:(id)arg1 didConfirmItemOfferForItem:(id)arg2 atIndexPath:(id)arg3;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (id)contentScrollView;
- (void)reloadData;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocation;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

