//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASCategoryProtocol-Protocol.h"

@class NSArray, NSNumber, NSString, SKUIClientContext;
@protocol SKUIArtworkProviding;

@interface ASNearbyCategory : NSObject <ASCategoryProtocol>
{
    NSArray *_children;
    NSNumber *_genreId;
    NSNumber *_groupingId;
    NSArray *_items;
    NSString *_name;
    NSString *_parentCategoryLabel;
    NSString *_shortName;
    NSString *_url;
    id <SKUIArtworkProviding> _cannedArtwork;
    SKUIClientContext *_clientContext;
}

@property(retain, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
@property(readonly, copy, nonatomic) id <SKUIArtworkProviding> cannedArtwork; // @synthesize cannedArtwork=_cannedArtwork;
@property(readonly, copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(readonly, copy, nonatomic) NSString *shortName; // @synthesize shortName=_shortName;
@property(readonly, copy, nonatomic) NSString *parentCategoryLabel; // @synthesize parentCategoryLabel=_parentCategoryLabel;
@property(readonly, copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, copy, nonatomic) NSNumber *groupingId; // @synthesize groupingId=_groupingId;
@property(readonly, copy, nonatomic) NSNumber *genreId; // @synthesize genreId=_genreId;
@property(readonly, copy, nonatomic) NSArray *children; // @synthesize children=_children;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

