//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIItemCellLayout.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, SKUICellScrollView, SKUIFocusedTouchGestureRecognizer, UIButton, UIView, _ASPurchasedCellContentView;

@interface ASPurchasedCellLayout : SKUIItemCellLayout <UIScrollViewDelegate>
{
    UIButton *_actionButton;
    SKUICellScrollView *_editScrollView;
    SKUIFocusedTouchGestureRecognizer *_touchCaptureRecognizer;
    _Bool _isNew;
    NSString *_subtitle;
    NSString *_subtitle2;
    NSString *_title;
    _ASPurchasedCellContentView *_cellContentView;
    UIView *_isNewView;
}

@property(retain, nonatomic) UIView *isNewView; // @synthesize isNewView=_isNewView;
@property(retain, nonatomic) _ASPurchasedCellContentView *cellContentView; // @synthesize cellContentView=_cellContentView;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *subtitle2; // @synthesize subtitle2=_subtitle2;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(nonatomic) _Bool isNew; // @synthesize isNew=_isNew;
- (void).cxx_destruct;
- (void)_removeTouchCaptureRecognizer;
- (void)_fixItemOfferButtonViewHierarchy;
- (void)_addTouchCaptureRecognizer;
- (void)_touchCaptureAction:(id)arg1;
- (void)_actionButtonAction:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)setItemState:(id)arg1 animated:(_Bool)arg2;
- (void)setItemOffer:(id)arg1;
- (void)setIconImage:(id)arg1;
- (void)layoutForItemOfferChange;
- (void)setBackgroundColor:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)setRestrictionsTextWithItem:(id)arg1 clientContext:(id)arg2;
@property(copy, nonatomic) NSString *restrictionsText;
@property(nonatomic) _Bool allowsEditing;
@property(copy, nonatomic) NSString *actionButtonTitle;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

