//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, SSFamilyCircle, SSFamilyMember;

@interface ASPurchasedPage : NSObject
{
    _Bool _didFilterInstalledApps;
    _Bool _hidesInstalledApps;
    long long _deviceType;
    SSFamilyCircle *_familyCircle;
    SSFamilyMember *_familyMember;
    NSArray *_items;
    NSString *_searchTerm;
}

@property(nonatomic) _Bool hidesInstalledApps; // @synthesize hidesInstalledApps=_hidesInstalledApps;
@property(nonatomic) _Bool didFilterInstalledApps; // @synthesize didFilterInstalledApps=_didFilterInstalledApps;
@property(copy, nonatomic) NSString *searchTerm; // @synthesize searchTerm=_searchTerm;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) SSFamilyMember *familyMember; // @synthesize familyMember=_familyMember;
@property(retain, nonatomic) SSFamilyCircle *familyCircle; // @synthesize familyCircle=_familyCircle;
@property(nonatomic) long long deviceType; // @synthesize deviceType=_deviceType;
- (void).cxx_destruct;

@end

