//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HSCloudClient, SSAppPurchaseHistoryDatabase;
@protocol OS_dispatch_queue;

@interface ASPurchasesDatabase : NSObject
{
    HSCloudClient *_cloudClient;
    SSAppPurchaseHistoryDatabase *_database;
    NSObject<OS_dispatch_queue> *_accessQueue;
}

+ (id)sharedPurchasesDatabase;
- (void).cxx_destruct;
- (void)_updateForFamilyMember:(id)arg1 withReason:(long long)arg2;
- (void)updateForFamilyMember:(id)arg1 withReason:(long long)arg2;
- (void)updateActiveAccountWithReason:(long long)arg1;
- (id)itemsWithPredicate:(id)arg1 sortColumn:(id)arg2 sortAscending:(_Bool)arg3 familyMember:(id)arg4;
- (void)hideItemWithStoreIdentifier:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

