//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIItem.h>

@class NSDate, SKUIItemOffer, SSPurchasableAppItem;

@interface ASPurchasedItem : SKUIItem
{
    SSPurchasableAppItem *_purchasableItem;
    SKUIItemOffer *_redownloadOffer;
    _Bool _hideable;
}

@property(nonatomic, getter=isHideable) _Bool hideable; // @synthesize hideable=_hideable;
- (void).cxx_destruct;
- (id)_ovalIconURLForSize:(long long)arg1;
- (_Bool)isNewsstandApp;
- (id)versionString;
- (long long)versionIdentifier;
- (float)userRating;
- (id)title;
@property(readonly, nonatomic) NSDate *purchasedDate;
- (id)productPageURLString;
- (id)primaryItemOffer;
- (long long)parentalControlsRank;
- (long long)numberOfUserRatings;
- (id)largestArtworkURL;
- (id)itemKindString;
- (long long)itemKind;
- (long long)itemIdentifier;
@property(readonly, nonatomic, getter=isSupportedOnIPhone) _Bool supportedOnIPhone;
@property(readonly, nonatomic, getter=isSupportedOnIPad) _Bool supportedOnIPad;
- (_Bool)isHiddenFromSpringBoard;
- (_Bool)hasMessagesExtension;
- (id)categoryName;
- (id)bundleIdentifier;
- (id)artworkURLForSize:(long long)arg1;
- (id)artistName;
- (struct _NSRange)ageBandRange;
@property(readonly, nonatomic, getter=isFamilyShareable) _Bool familyShareable;
- (id)initWithPurchasableAppItem:(id)arg1;

@end

