//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ASQuickActionsController : NSObject
{
}

+ (void)updateShortcutItems;
+ (void)processShortcutItem:(id)arg1 applicationController:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)sharedInstance;
- (id)_shortcutItemsAndIncludeUpdates:(_Bool)arg1;
- (id)_shortcutItems;
- (void)_updateStoreDidChange:(id)arg1;
- (void)_accountStoreDidChange:(id)arg1;
- (void)processShortcutItem:(id)arg1 applicationController:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)init;

@end

