//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ASCategoriesBaseDatasource.h"

@protocol ASCategoriesDatasourceDelegate, ASCategoryProtocol;

@interface ASSubcategoriesDatasource : ASCategoriesBaseDatasource
{
    id <ASCategoryProtocol> _parentCategory;
    id <ASCategoriesDatasourceDelegate> _delegate;
}

- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void).cxx_destruct;
- (unsigned long long)numberOfItemsInSection:(unsigned long long)arg1;
- (unsigned long long)numberOfSections;
- (id)title;
- (id)categories;
- (id)titleForSection:(unsigned long long)arg1;
- (unsigned long long)headerTypeForSection:(unsigned long long)arg1;
- (id)categoryTitleAtIndexPath:(id)arg1;
- (id)categoryAtIndexPath:(id)arg1;
- (void)fetchCategories;
- (id)initWithParentCategory:(id)arg1;

@end

