//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIItem.h>

@class NSString;

@interface ASUpdateItem : SKUIItem
{
    NSString *_lastUpdateDateString;
    _Bool _systemApp;
    NSString *_updateDescription;
}

@property(readonly, nonatomic) NSString *updateDescription; // @synthesize updateDescription=_updateDescription;
@property(readonly, nonatomic, getter=isSystemApp) _Bool systemApp; // @synthesize systemApp=_systemApp;
@property(readonly, nonatomic) NSString *lastUpdateDateString; // @synthesize lastUpdateDateString=_lastUpdateDateString;
- (void).cxx_destruct;
- (id)description;
- (id)initWithLookupDictionary:(id)arg1;

@end

