//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIItemTableViewCell.h>

@class ASUpdateCellLayout;

@interface ASUpdateTableViewCell : SKUIItemTableViewCell
{
    ASUpdateCellLayout *_layout;
}

@property(readonly, nonatomic) ASUpdateCellLayout *layout; // @synthesize layout=_layout;
- (void).cxx_destruct;
- (void)configureForItem:(id)arg1 rowIndex:(long long)arg2;
- (void)configureForItem:(id)arg1 rowIndex:(long long)arg2 textLayout:(id)arg3 numberOfLines:(long long)arg4 isPad:(_Bool)arg5;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

