//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIItemCellLayout.h>

@class NSString, SKUITextBoxView, UILabel;

@interface ASUpdateCellLayout : SKUIItemCellLayout
{
    _Bool _allowsOnlyUpdateButton;
    _Bool _isPad;
    UILabel *_lastUpdateDateLabel;
    _Bool _showsWhatsNewButton;
    UILabel *_titleLabel;
    UILabel *_versionLabel;
    UILabel *_whatsNewButtonLabel;
    SKUITextBoxView *_whatsNewTextBox;
    double _whatsNewWidth;
}

@property(nonatomic) double whatsNewWidth; // @synthesize whatsNewWidth=_whatsNewWidth;
@property(nonatomic) _Bool showsWhatsNewButton; // @synthesize showsWhatsNewButton=_showsWhatsNewButton;
@property(nonatomic, getter=isPad) _Bool pad; // @synthesize pad=_isPad;
@property(nonatomic) _Bool allowsOnlyUpdateButton; // @synthesize allowsOnlyUpdateButton=_allowsOnlyUpdateButton;
- (void).cxx_destruct;
- (id)_whatsNewButtonLabel;
- (void)layoutForItemOfferChange;
- (void)setBackgroundColor:(id)arg1;
- (void)layoutSubviews;
- (_Bool)displaysItemOfferButton;
@property(copy, nonatomic) NSString *versionString;
@property(copy, nonatomic) NSString *title;
- (void)setWhatsNewWithTextFrame:(struct __CTFrame *)arg1 numberOfVisibleLines:(long long)arg2;
@property(copy, nonatomic) NSString *lastUpdateDateString;

@end

