//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SKUIItem, SKUIItemGridViewController;

@protocol SKUIItemGridDelegate <NSObject>

@optional
- (void)itemGridWillBeginDragging:(SKUIItemGridViewController *)arg1;
- (void)itemGrid:(SKUIItemGridViewController *)arg1 didSelectItem:(SKUIItem *)arg2 atIndex:(long long)arg3;
- (void)itemGrid:(SKUIItemGridViewController *)arg1 didPerformEditActionForItem:(SKUIItem *)arg2 atIndex:(long long)arg3;
@end

