//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKitUI/SKUIJSITunesStore.h>

#import "SKUIJSITunesStoreAdAdditions-Protocol.h"

@interface SKUIJSITunesStore (ASAdURLAdditions) <SKUIJSITunesStoreAdAdditions>
+ (void)setAdsEnabled:(_Bool)arg1;
+ (_Bool)adsEnabled;
- (id)as_undefinedResultForCallback:(id)arg1;
- (void)_pushNewSponsoredSearchCanary:(id)arg1;
- (void)getSponsoredSearchAdServerURL:(id)arg1;
- (void)getSponsoredSearchTargetingDataAndId:(id)arg1;
- (void)getSponsoredSearchTargetingData:(id)arg1;
- (void)getToroID:(id)arg1;
@end

