//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSExport-Protocol.h"

@class JSValue;

@protocol SKUIJSITunesStoreAdAdditions <JSExport>
- (void)getSponsoredSearchAdServerURL:(JSValue *)arg1;
- (void)getSponsoredSearchTargetingDataAndId:(JSValue *)arg1;
- (void)getSponsoredSearchTargetingData:(JSValue *)arg1;
- (void)getToroID:(JSValue *)arg1;
@end

